# Generated by Django 2.2.25 on 2022-01-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookconfiguration',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='webhookconfiguration',
            name='base_url',
        ),
        migrations.AddField(
            model_name='webhookconfiguration',
            name='secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='webhookconfiguration',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
